### ISSUE TITLE
[polybar] Configure me!

### ISSUE THREAD

**Issue by elihunter173** [elihunter173/dotfiles#7]
Currently, I am just using the example config, which is just serviceable.

## TODO
* [x] Remove extraneous information. (Who needs to know CPU temp at all times?)
* [x] Remove unnecessary modules. (I don't need bpwsm modules)
* [x] Show battery percentage for all batteries. (Labelled!)
* [ ] Show sink volume for all sinks. (Labelled!)
* [x] Make colorscheme base16 compliant.
* [ ] Make the bar pretty.
* [ ] Add quality of life widgets.

**Comment by elihunter173** [comment]
I actually finished this months ago and forgot to update this. I'm now cleaning up my issues.
